### PR TITLE
Explicit mapping

### PR DESCRIPTION
**Pull request by chaowlert**
Hi eric, please help review this PR. This PR included your change on extension method. By merging this PR will accept your PR.

I don't fully understand how RequireExplicitMapping works.
From what I understand after your posted issues is RequireExplicitMapping will only apply to Class (not List and Primitive).

Here is scenario.

```
class Parent {
    public string Id { get; set; }
    public List<Child> Items { get; set; }
}
class Child {
    public List<int> Blah { get; set; }
}

var result = TypeAdapter.Adapt<Parent[], List<Parent>>(src);
```

if we have only `TypeAdaptConfig<Parent, Parent>`, we will throw explicit alert on (Child, Child).

But if we have both `TypeAdaptConfig<Parent, Parent>` and `TypeAdaptConfig<Child, Child>`, mapping will be succeeded (we will not validate list and primitives).

### CODE REVIEW

**Comment by chaowlert** [comment]
PS. Could you help configure AppVayor to build only Mapster.sln?

**Comment by eric-swann-q2** [comment]
I think the behavior you have described here is as designed...I believe this is as it should be in this case.

**Comment by eric-swann-q2** [comment]
I'll take a look at appveyor

**Comment by eswann** [comment]
AppVeyor is fixed...I"m going to merge this pull request and do some more testing on it.

**Pull request merged**
